// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDExHtdq0NgJNhIFUetxOConpRf91o4x7E',
    appId: '1:1044751998227:android:7c08fd9ff8fd5e571e8ee6',
    messagingSenderId: '1044751998227',
    projectId: 'deltamobile-507be',
    storageBucket: 'deltamobile-507be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbUuYCMVnNmmATlHr8d7yX29yiWft9UR4',
    appId: '1:1044751998227:ios:8101360c5623d8fd1e8ee6',
    messagingSenderId: '1044751998227',
    projectId: 'deltamobile-507be',
    storageBucket: 'deltamobile-507be.firebasestorage.app',
    iosBundleId: 'com.example.deltaMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNxrlyq03btaqoV1DFBSjukRPBV-64Y4',
    appId: '1:1044751998227:web:9e3f88ebda32d8051e8ee6',
    messagingSenderId: '1044751998227',
    projectId: 'deltamobile-507be',
    authDomain: 'deltamobile-507be.firebaseapp.com',
    storageBucket: 'deltamobile-507be.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbUuYCMVnNmmATlHr8d7yX29yiWft9UR4',
    appId: '1:1044751998227:ios:8101360c5623d8fd1e8ee6',
    messagingSenderId: '1044751998227',
    projectId: 'deltamobile-507be',
    storageBucket: 'deltamobile-507be.firebasestorage.app',
    iosBundleId: 'com.example.deltaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPNxrlyq03btaqoV1DFBSjukRPBV-64Y4',
    appId: '1:1044751998227:web:8fd98fc59ea050081e8ee6',
    messagingSenderId: '1044751998227',
    projectId: 'deltamobile-507be',
    authDomain: 'deltamobile-507be.firebaseapp.com',
    storageBucket: 'deltamobile-507be.firebasestorage.app',
  );

}